# Generated by Django 3.1.6 on 2021-02-11 15:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': '', 'verbose_name': 'diary entry', 'verbose_name_plural': 'diary entries'},
        ),
        migrations.AddField(
            model_name='diary',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diary',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
