# Generated by Django 3.1.6 on 2021-02-11 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0002_auto_20210211_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': ('-datetime_created',), 'verbose_name': 'diary entry', 'verbose_name_plural': 'diary entries'},
        ),
    ]
