# Generated by Django 3.1.6 on 2021-02-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0005_auto_20210218_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
