# Generated by Django 3.1.6 on 2021-03-03 13:51

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='updated on')),
                ('date', models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)])),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='weight (kg)')),
                ('image', models.ImageField(blank=True, help_text='Upload an optional progress picture for this day.', null=True, upload_to='images/progress_pictures', verbose_name='progress picture')),
                ('notes', models.TextField(blank=True, max_length=1000, null=True, verbose_name='notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'progress log',
                'verbose_name_plural': 'progress logs',
            },
        ),
        migrations.AddConstraint(
            model_name='progress',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_date'),
        ),
    ]
