# Generated by Django 3.1.4 on 2021-02-09 13:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progress', '0002_auto_20210209_1315'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Log',
            new_name='Progress',
        ),
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name': 'Progress', 'verbose_name_plural': 'Progress'},
        ),
    ]
