# Generated by Django 3.1.6 on 2021-02-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_auto_20210212_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='images',
                verbose_name='progress picture',
            ),
        ),
    ]
