# Generated by Django 3.1.6 on 2021-02-27 13:46

import datetime

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_auto_20210227_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='date',
            field=models.DateField(
                default=django.utils.timezone.now,
                validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)],
            ),
        ),
        migrations.AlterField(
            model_name='progress',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='Upload an optional progress picture for this day.',
                null=True,
                upload_to='images',
                verbose_name='progress picture',
            ),
        ),
    ]
