# Generated by Django 3.1.6 on 2021-02-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_auto_20210227_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='Upload an optional progress picture for this day.',
                null=True,
                upload_to='images/progress_pictures',
                verbose_name='progress picture',
            ),
        ),
        migrations.AlterField(
            model_name='progress',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
