# Generated by Django 3.1.4 on 2021-02-06 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='target_carbohydrate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='target_energy',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='target_fat',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='target_fibre',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='target_protein',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='target_salt',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='target_saturates',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='target_sugars',
        ),
    ]
