# Generated by Django 3.1.6 on 2021-02-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210206_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='target_carbohydrate',
            field=models.DecimalField(decimal_places=1, default=260, max_digits=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_energy',
            field=models.IntegerField(default=2000, verbose_name='energy (kcal)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_fat',
            field=models.DecimalField(decimal_places=1, default=70, max_digits=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_fibre',
            field=models.DecimalField(decimal_places=1, default=30, max_digits=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_protein',
            field=models.DecimalField(decimal_places=1, default=50, max_digits=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_salt',
            field=models.DecimalField(decimal_places=2, default=6, max_digits=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_saturates',
            field=models.DecimalField(decimal_places=1, default=20, max_digits=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_sugars',
            field=models.DecimalField(decimal_places=1, default=90, max_digits=4),
        ),
    ]
