# Generated by Django 3.1.6 on 2021-02-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210211_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='target_carbohydrate',
            new_name='carbohydrate',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='target_energy',
            new_name='energy',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='target_fat',
            new_name='fat',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='target_fibre',
            new_name='fibre',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='target_protein',
            new_name='protein',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='target_salt',
            new_name='salt',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='target_saturates',
            new_name='saturates',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='target_sugars',
            new_name='sugars',
        ),
    ]
