# Generated by Django 3.1.6 on 2021-02-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210212_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='carbohydrate',
            field=models.DecimalField(decimal_places=1, default=260, max_digits=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='energy',
            field=models.IntegerField(default=2000, verbose_name='energy (kcal)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fat',
            field=models.DecimalField(decimal_places=1, default=70, max_digits=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fibre',
            field=models.DecimalField(decimal_places=1, default=30, max_digits=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='protein',
            field=models.DecimalField(decimal_places=1, default=50, max_digits=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='salt',
            field=models.DecimalField(decimal_places=2, default=6, max_digits=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='saturates',
            field=models.DecimalField(decimal_places=1, default=20, max_digits=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sugars',
            field=models.DecimalField(decimal_places=1, default=90, max_digits=4),
        ),
    ]
