# Generated by Django 3.1.6 on 2021-02-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210212_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='height (cm)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(
                blank=True,
                choices=[('M', 'Male'), ('F', 'Female')],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                verbose_name='weight (kg)',
            ),
        ),
    ]
