# Generated by Django 3.1.6 on 2021-02-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20210227_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='calories_per_kg',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='carbohydrate_pct',
            field=models.PositiveIntegerField(null=True, verbose_name='carbohydrate percent'),
        ),
        migrations.AddField(
            model_name='profile',
            name='carbohydrate_per_kg',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fat_pct',
            field=models.PositiveIntegerField(null=True, verbose_name='fat percent'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fat_per_kg',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='protein_pct',
            field=models.PositiveIntegerField(null=True, verbose_name='protein percent'),
        ),
        migrations.AddField(
            model_name='profile',
            name='protein_per_kg',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(
                blank=True,
                choices=[
                    ('SD', 'Sedentary'),
                    ('LA', 'Lightly Active'),
                    ('MA', 'Moderately Active'),
                    ('VA', 'Very Active'),
                    ('EA', 'Extra Active'),
                ],
                help_text='\n        <ul>\n        <li>Sedentary - Little to no exercise.</li>\n        <li>Light Activity - Exercise 1 to 2 days a week.</li>\n        <li>Moderate Activity - Exercise 3 to 5 days a week.</li>\n        <li>High Activity - Exercise 6 to 7 days a week.</li>\n        <li>Very High Activity - Exercise 6 to 7 days a week, and a physical job.</li>\n        </ul>\n        ',
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='calculation_method',
            field=models.CharField(
                blank=True,
                choices=[('REC', 'Recommended'), ('PER', 'Percent'), ('GRA', 'Grams'), ('CUS', 'Custom')],
                editable=False,
                help_text="Records the method that was used to set the user's macronutrient targets.",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='energy',
            field=models.PositiveIntegerField(default=2000, verbose_name='energy (kcal)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.CharField(
                blank=True,
                choices=[('LW', 'Lose Fat'), ('MW', 'Maintain Weight'), ('GW', 'Build Muscle')],
                help_text='\n        <ul>\n        <li>Lose Fat.</li>\n        <li>Maintain Weight.</li>\n        <li>Gain Muscle.</li>\n        </ul>\n        ',
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='height (cm)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(
                blank=True,
                default='images/profile_pictures/default.png',
                null=True,
                upload_to='images/profile_pictures',
                verbose_name='profile picture',
            ),
        ),
    ]
