# Generated by Django 3.1.6 on 2021-02-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20210228_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='calculation_method',
            field=models.CharField(
                blank=True,
                choices=[('REC', 'Recommended'), ('PER', 'Percent'), ('GRA', 'Grams'), ('CUS', 'Custom')],
                editable=False,
                help_text="Calculation method used to set the user's macronutrient targets.",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='calories_per_kg',
            field=models.PositiveIntegerField(
                blank=True, help_text='The amount of calories (kcal) per kilogram of body weight.', null=True
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='carbohydrate_pct',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='\n        Percentage of daily calories from carbohydrates.\n        ',
                null=True,
                verbose_name='carbohydrate percent',
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='carbohydrate_per_kg',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='The amount of carbohydrates (in grams) per kilogram of body weight.',
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fat_pct',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='\n        Percentage of daily calories from fat.\n        ',
                null=True,
                verbose_name='fat percent',
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fat_per_kg',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='The amount of fat (in grams) per kilogram of body weight.',
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal_weight',
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text='Used to determine duration required to reach weight goal.',
                max_digits=4,
                null=True,
                verbose_name='goal weight (kg)',
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='protein_pct',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='\n        Percentage of daily calories from protein.\n        ',
                null=True,
                verbose_name='protein percent',
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='protein_per_kg',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='The amount of protein (in grams) per kilogram of body weight.',
                max_digits=4,
                null=True,
            ),
        ),
    ]
