# Generated by Django 3.1.6 on 2021-03-03 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='updated on')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional.', max_length=1000, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'saved meal',
                'verbose_name_plural': 'saved meals',
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='updated on')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.meal')),
            ],
            options={
                'verbose_name': 'meal content',
                'verbose_name_plural': 'meal contents',
            },
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_meal_name'),
        ),
    ]
