# Generated by Django 3.1.4 on 2021-02-09 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_food_active'),
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'verbose_name': 'meal', 'verbose_name_plural': 'saved meals'},
        ),
        migrations.AlterField(
            model_name='meal',
            name='item_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_items_1', to='food.food'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='item_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_items_2', to='food.food'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='item_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_items_3', to='food.food'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='item_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_items_4', to='food.food'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='item_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_items_5', to='food.food'),
        ),
    ]
