# Generated by Django 3.1.6 on 2021-02-21 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_auto_20210220_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='item_1',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='item_10',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='item_10_quantity',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='item_1_quantity',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='item_2',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='item_2_quantity',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='item_3',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='item_3_quantity',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='item_4',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='item_4_quantity',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='item_5',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='item_5_quantity',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='item_6',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='item_6_quantity',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='item_7',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='item_7_quantity',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='item_8',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='item_8_quantity',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='item_9',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='item_9_quantity',
        ),
    ]
