# Generated by Django 3.1.6 on 2021-02-21 23:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_auto_20210218_2318'),
        ('meals', '0007_auto_20210221_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.TextField(blank=True, help_text='Optional.', max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.meal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
