# Generated by Django 3.1.6 on 2021-02-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0010_remove_meal_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
