# Generated by Django 3.1.6 on 2021-02-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0012_auto_20210226_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealitem',
            options={'verbose_name': 'meal content', 'verbose_name_plural': 'meal contents'},
        ),
    ]
