# Generated by Django 3.1.6 on 2021-02-28 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0013_auto_20210228_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'verbose_name': 'saved meal', 'verbose_name_plural': 'saved meals'},
        ),
    ]
