# Generated by Django 3.1.6 on 2021-03-04 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_post_user_created_related', related_query_name='blog_post_user_created_rquery', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_post_user_updated_related', related_query_name='blog_post_user_updated_rquery', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
    ]
