# Generated by Django 3.1.4 on 2021-02-06 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('user_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_brand_user_created_related', related_query_name='food_brand_user_created_rquery', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_brand_user_updated_related', related_query_name='food_brand_user_updated_rquery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('user_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_category_user_created_related', related_query_name='food_category_user_created_rquery', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_category_user_updated_related', related_query_name='food_category_user_updated_rquery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('energy', models.IntegerField(verbose_name='energy (kcal)')),
                ('fat', models.DecimalField(decimal_places=1, max_digits=4)),
                ('saturates', models.DecimalField(decimal_places=1, max_digits=4)),
                ('carbohydrate', models.DecimalField(decimal_places=1, max_digits=4)),
                ('sugars', models.DecimalField(decimal_places=1, max_digits=4)),
                ('fibre', models.DecimalField(decimal_places=1, max_digits=4)),
                ('protein', models.DecimalField(decimal_places=1, max_digits=4)),
                ('salt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('data_value', models.IntegerField()),
                ('data_measurement', models.CharField(choices=[('g', 'g'), ('ml', 'ml'), ('srv', 'serving')], max_length=50)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.brand')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.category')),
                ('user_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_food_user_created_related', related_query_name='food_food_user_created_rquery', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_food_user_updated_related', related_query_name='food_food_user_updated_rquery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'food',
                'verbose_name_plural': 'food',
                'ordering': ('name',),
            },
        ),
    ]
