# Generated by Django 3.1.6 on 2021-03-03 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='updated on')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('user_created', models.ForeignKey(default='c64c16ee-fc7f-45c3-a84b-a81a6a29d5d6', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_brand_user_created_related', related_query_name='food_brand_user_created_rquery', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('user_updated', models.ForeignKey(default='c64c16ee-fc7f-45c3-a84b-a81a6a29d5d6', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_brand_user_updated_related', related_query_name='food_brand_user_updated_rquery', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='updated on')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('user_created', models.ForeignKey(default='c64c16ee-fc7f-45c3-a84b-a81a6a29d5d6', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_category_user_created_related', related_query_name='food_category_user_created_rquery', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('user_updated', models.ForeignKey(default='c64c16ee-fc7f-45c3-a84b-a81a6a29d5d6', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_category_user_updated_related', related_query_name='food_category_user_updated_rquery', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('energy', models.IntegerField(verbose_name='calories (kcal)')),
                ('fat', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='fat (g)')),
                ('saturates', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='saturates (g)')),
                ('carbohydrate', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='carbohydrate (g)')),
                ('sugars', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='sugars (g)')),
                ('fibre', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='fibre (g)')),
                ('protein', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='protein (g)')),
                ('salt', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='salt (g)')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='updated on')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('data_value', models.IntegerField()),
                ('data_measurement', models.CharField(choices=[('g', 'g'), ('ml', 'ml'), ('srv', 'serving')], max_length=50)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('active', models.BooleanField(default=True, help_text='Designates whether this food is displayed in the database. Unselect this instead of deleting food.')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.category')),
                ('user_created', models.ForeignKey(default='c64c16ee-fc7f-45c3-a84b-a81a6a29d5d6', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_food_user_created_related', related_query_name='food_food_user_created_rquery', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('user_updated', models.ForeignKey(default='c64c16ee-fc7f-45c3-a84b-a81a6a29d5d6', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_food_user_updated_related', related_query_name='food_food_user_updated_rquery', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'food',
                'verbose_name_plural': 'food',
                'ordering': ('name',),
            },
        ),
        migrations.AddConstraint(
            model_name='food',
            constraint=models.UniqueConstraint(fields=('name', 'brand'), name='unique_name_brand'),
        ),
    ]
