# Generated by Django 3.1.4 on 2021-02-06 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='datetime_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='datetime_updated',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='datetime_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='datetime_updated',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='datetime_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='datetime_updated',
            new_name='updated',
        ),
    ]
