# Generated by Django 3.1.4 on 2021-02-06 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20210206_0613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='created',
            new_name='datetime_created',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='updated',
            new_name='datetime_updated',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='created',
            new_name='datetime_created',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='updated',
            new_name='datetime_updated',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='created',
            new_name='datetime_created',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='updated',
            new_name='datetime_updated',
        ),
    ]
