# Generated by Django 3.1.4 on 2021-02-08 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0003_auto_20210206_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='user_created',
            field=models.ForeignKey(default='admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_brand_user_created_related', related_query_name='food_brand_user_created_rquery', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brand',
            name='user_updated',
            field=models.ForeignKey(default='admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_brand_user_updated_related', related_query_name='food_brand_user_updated_rquery', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='user_created',
            field=models.ForeignKey(default='admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_category_user_created_related', related_query_name='food_category_user_created_rquery', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='user_updated',
            field=models.ForeignKey(default='admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_category_user_updated_related', related_query_name='food_category_user_updated_rquery', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='food.category'),
        ),
        migrations.AlterField(
            model_name='food',
            name='data_measurement',
            field=models.CharField(choices=[('g', 'g'), ('ml', 'ml'), ('srv', 'serving')], default='g', max_length=50),
        ),
        migrations.AlterField(
            model_name='food',
            name='data_value',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='user_created',
            field=models.ForeignKey(default='admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_food_user_created_related', related_query_name='food_food_user_created_rquery', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='food',
            name='user_updated',
            field=models.ForeignKey(default='admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_food_user_updated_related', related_query_name='food_food_user_updated_rquery', to=settings.AUTH_USER_MODEL),
        ),
    ]
