# Generated by Django 3.1.4 on 2021-02-08 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20210208_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={
                'ordering': ('-datetime_created',),
                'verbose_name': 'food',
                'verbose_name_plural': 'food',
            },
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.category'),
        ),
    ]
