# Generated by Django 3.1.4 on 2021-02-09 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20210208_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ('name',), 'verbose_name': 'food', 'verbose_name_plural': 'food'},
        ),
    ]
