# Generated by Django 3.1.4 on 2021-02-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20210209_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='active',
            field=models.BooleanField(default=True, help_text='Designates whether the food is displayed in the database or not. Unselect this instead of deleting food.'),
        ),
    ]
