# Generated by Django 3.1.6 on 2021-02-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_food_active'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='food',
            constraint=models.UniqueConstraint(fields=('name', 'brand'), name='unique_name_brand'),
        ),
    ]
