# Generated by Django 3.1.6 on 2021-02-18 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0009_auto_20210212_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='user_created',
            field=models.ForeignKey(default='c64c16ee-fc7f-45c3-a84b-a81a6a29d5d6', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_brand_user_created_related', related_query_name='food_brand_user_created_rquery', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='user_updated',
            field=models.ForeignKey(default='c64c16ee-fc7f-45c3-a84b-a81a6a29d5d6', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_brand_user_updated_related', related_query_name='food_brand_user_updated_rquery', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='category',
            name='user_created',
            field=models.ForeignKey(default='c64c16ee-fc7f-45c3-a84b-a81a6a29d5d6', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_category_user_created_related', related_query_name='food_category_user_created_rquery', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='category',
            name='user_updated',
            field=models.ForeignKey(default='c64c16ee-fc7f-45c3-a84b-a81a6a29d5d6', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_category_user_updated_related', related_query_name='food_category_user_updated_rquery', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='food',
            name='active',
            field=models.BooleanField(default=True, help_text='Designates whether this food is displayed in the database. Unselect this instead of deleting food.'),
        ),
        migrations.AlterField(
            model_name='food',
            name='data_measurement',
            field=models.CharField(choices=[('g', 'g'), ('ml', 'ml'), ('srv', 'serving')], max_length=50),
        ),
        migrations.AlterField(
            model_name='food',
            name='data_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='user_created',
            field=models.ForeignKey(default='c64c16ee-fc7f-45c3-a84b-a81a6a29d5d6', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_food_user_created_related', related_query_name='food_food_user_created_rquery', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='food',
            name='user_updated',
            field=models.ForeignKey(default='c64c16ee-fc7f-45c3-a84b-a81a6a29d5d6', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_food_user_updated_related', related_query_name='food_food_user_updated_rquery', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
    ]
