# Generated by Django 3.1.6 on 2021-02-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_auto_20210218_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbohydrate',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='carbohydrate (g)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='energy',
            field=models.IntegerField(verbose_name='calories (kcal)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='fat (g)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='fibre',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='fibre (g)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='protein (g)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='salt',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='salt (g)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='saturates',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='saturates (g)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='sugars',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='sugars (g)'),
        ),
    ]
