# Generated by Django 3.1.6 on 2021-02-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_auto_20210226_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created on'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated on'),
        ),
        migrations.AlterField(
            model_name='category',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created on'),
        ),
        migrations.AlterField(
            model_name='category',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated on'),
        ),
        migrations.AlterField(
            model_name='food',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created on'),
        ),
        migrations.AlterField(
            model_name='food',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated on'),
        ),
    ]
